import Head from 'next/head'
import Image from 'next/image'
import FundingPyconkit from '../components/contribute/FundingPyconkit'
import GotoContribute from '../components/contribute/GotoContribute'
import Header from '../components/Header'
import MainView from '../components/main/MainView'
import PyconLogo from '../components/PyconLogo'
import AboutContext from '../components/about/AboutContext'
import { GotoSupport, GotoCoc } from '../components/main/GotoSection'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <MainView />
        <GotoContribute />
        <FundingPyconkit />
        <AboutContext />
        <GotoSupport />
        <GotoCoc />
      </main>

      <footer>
      </footer>
    </div>
  )
}
